### ISSUE TITLE
Posición de quicksand no sincronizada

### ISSUE THREAD

**Issue by Irenko85** [Irenko85/boulder-toss#27]
Cuando un jugador lanza la habilidad de quicksand y aparece en el suelo, no tienen las mismas posiciones para los 2 jugadores. Supongo que se debería enviar la posición en la que spawneará para luego sincronizarlas.

![image](https://github.com/Irenko85/boulder-toss/assets/114310340/e3ea3af3-aea6-469a-99a6-8b9a79232925)

**Comment by CrisIsla** [comment]
El problema venia de que el personaje simulado solo rota el rig en x, por lo que si se lanzaba la granada hacia arriba o hacia abajo no habia forma de saberlo. Se solucionó pasando como parametro la direccion de lanzamiento en el rpc.
