### ISSUE TITLE
Bug con el personaje al girar la cámara

### ISSUE THREAD

**Issue by Irenko85** [Irenko85/boulder-toss#28]
Si el jugador 1 gira la cámara hasta cierto punto, en la ventana del jugador 2 se ve el personaje del jugador 1 bugeado. Esto ocurre independiente del jugador que se está controlando

Pasos para reproducir:
1. Ver ambas ventanas para diferenciar los personajes
2. Girar la cámara del jugador 1 o 2 y ver el comportamiento en la ventana que no se hizo el movimiento de cámara

https://github.com/Irenko85/boulder-toss/assets/114310340/700c73a1-229f-4247-9afe-e89f173029c5

**Comment by fjararibet** [comment]
Duplicado de issue #11

**Comment by CrisIsla** [comment]
Se arreglo cambiando la rotacion por quaternion, y usando slerp en vez de lerp.
